// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: lspclient.proto

package lspclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// github.com/nayutaco/NayutaHub2LspdProto
type IntegrityResult int32

const (
	IntegrityResult_INTEGRITYRESULT_NONE IntegrityResult = 0
	IntegrityResult_INTEGRITYRESULT_OK   IntegrityResult = 1
	IntegrityResult_INTEGRITYRESULT_NG   IntegrityResult = 2
)

// Enum value maps for IntegrityResult.
var (
	IntegrityResult_name = map[int32]string{
		0: "INTEGRITYRESULT_NONE",
		1: "INTEGRITYRESULT_OK",
		2: "INTEGRITYRESULT_NG",
	}
	IntegrityResult_value = map[string]int32{
		"INTEGRITYRESULT_NONE": 0,
		"INTEGRITYRESULT_OK":   1,
		"INTEGRITYRESULT_NG":   2,
	}
)

func (x IntegrityResult) Enum() *IntegrityResult {
	p := new(IntegrityResult)
	*p = x
	return p
}

func (x IntegrityResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntegrityResult) Descriptor() protoreflect.EnumDescriptor {
	return file_lspclient_proto_enumTypes[0].Descriptor()
}

func (IntegrityResult) Type() protoreflect.EnumType {
	return &file_lspclient_proto_enumTypes[0]
}

func (x IntegrityResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntegrityResult.Descriptor instead.
func (IntegrityResult) EnumDescriptor() ([]byte, []int) {
	return file_lspclient_proto_rawDescGZIP(), []int{0}
}

type SubmarineCreateKeysResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Preimage     []byte `protobuf:"bytes,1,opt,name=preimage,proto3" json:"preimage,omitempty"`
	PaymentHash  []byte `protobuf:"bytes,2,opt,name=payment_hash,json=paymentHash,proto3" json:"payment_hash,omitempty"`
	RepayPrivkey []byte `protobuf:"bytes,3,opt,name=repay_privkey,json=repayPrivkey,proto3" json:"repay_privkey,omitempty"`
	RepayPubkey  []byte `protobuf:"bytes,4,opt,name=repay_pubkey,json=repayPubkey,proto3" json:"repay_pubkey,omitempty"`
}

func (x *SubmarineCreateKeysResult) Reset() {
	*x = SubmarineCreateKeysResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lspclient_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmarineCreateKeysResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmarineCreateKeysResult) ProtoMessage() {}

func (x *SubmarineCreateKeysResult) ProtoReflect() protoreflect.Message {
	mi := &file_lspclient_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmarineCreateKeysResult.ProtoReflect.Descriptor instead.
func (*SubmarineCreateKeysResult) Descriptor() ([]byte, []int) {
	return file_lspclient_proto_rawDescGZIP(), []int{0}
}

func (x *SubmarineCreateKeysResult) GetPreimage() []byte {
	if x != nil {
		return x.Preimage
	}
	return nil
}

func (x *SubmarineCreateKeysResult) GetPaymentHash() []byte {
	if x != nil {
		return x.PaymentHash
	}
	return nil
}

func (x *SubmarineCreateKeysResult) GetRepayPrivkey() []byte {
	if x != nil {
		return x.RepayPrivkey
	}
	return nil
}

func (x *SubmarineCreateKeysResult) GetRepayPubkey() []byte {
	if x != nil {
		return x.RepayPubkey
	}
	return nil
}

type SubmarineRegisterResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HtlcPubkey    []byte `protobuf:"bytes,1,opt,name=htlc_pubkey,json=htlcPubkey,proto3" json:"htlc_pubkey,omitempty"`
	Script        []byte `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	ScriptAddress string `protobuf:"bytes,3,opt,name=script_address,json=scriptAddress,proto3" json:"script_address,omitempty"`
	Height        uint32 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *SubmarineRegisterResult) Reset() {
	*x = SubmarineRegisterResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lspclient_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmarineRegisterResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmarineRegisterResult) ProtoMessage() {}

func (x *SubmarineRegisterResult) ProtoReflect() protoreflect.Message {
	mi := &file_lspclient_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmarineRegisterResult.ProtoReflect.Descriptor instead.
func (*SubmarineRegisterResult) Descriptor() ([]byte, []int) {
	return file_lspclient_proto_rawDescGZIP(), []int{1}
}

func (x *SubmarineRegisterResult) GetHtlcPubkey() []byte {
	if x != nil {
		return x.HtlcPubkey
	}
	return nil
}

func (x *SubmarineRegisterResult) GetScript() []byte {
	if x != nil {
		return x.Script
	}
	return nil
}

func (x *SubmarineRegisterResult) GetScriptAddress() string {
	if x != nil {
		return x.ScriptAddress
	}
	return ""
}

func (x *SubmarineRegisterResult) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type SubmarineDetectResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InTxid   string `protobuf:"bytes,1,opt,name=in_txid,json=inTxid,proto3" json:"in_txid,omitempty"`
	InIndex  int32  `protobuf:"varint,2,opt,name=in_index,json=inIndex,proto3" json:"in_index,omitempty"`
	InAmount int64  `protobuf:"varint,3,opt,name=in_amount,json=inAmount,proto3" json:"in_amount,omitempty"`
	InHeight uint32 `protobuf:"varint,4,opt,name=in_height,json=inHeight,proto3" json:"in_height,omitempty"`
}

func (x *SubmarineDetectResult) Reset() {
	*x = SubmarineDetectResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lspclient_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmarineDetectResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmarineDetectResult) ProtoMessage() {}

func (x *SubmarineDetectResult) ProtoReflect() protoreflect.Message {
	mi := &file_lspclient_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmarineDetectResult.ProtoReflect.Descriptor instead.
func (*SubmarineDetectResult) Descriptor() ([]byte, []int) {
	return file_lspclient_proto_rawDescGZIP(), []int{2}
}

func (x *SubmarineDetectResult) GetInTxid() string {
	if x != nil {
		return x.InTxid
	}
	return ""
}

func (x *SubmarineDetectResult) GetInIndex() int32 {
	if x != nil {
		return x.InIndex
	}
	return 0
}

func (x *SubmarineDetectResult) GetInAmount() int64 {
	if x != nil {
		return x.InAmount
	}
	return 0
}

func (x *SubmarineDetectResult) GetInHeight() uint32 {
	if x != nil {
		return x.InHeight
	}
	return 0
}

type SubmarineRepayData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Privkey []byte `protobuf:"bytes,1,opt,name=privkey,proto3" json:"privkey,omitempty"`
	Script  []byte `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Txid    string `protobuf:"bytes,3,opt,name=txid,proto3" json:"txid,omitempty"`
	Index   int32  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	Amount  int64  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *SubmarineRepayData) Reset() {
	*x = SubmarineRepayData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lspclient_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmarineRepayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmarineRepayData) ProtoMessage() {}

func (x *SubmarineRepayData) ProtoReflect() protoreflect.Message {
	mi := &file_lspclient_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmarineRepayData.ProtoReflect.Descriptor instead.
func (*SubmarineRepayData) Descriptor() ([]byte, []int) {
	return file_lspclient_proto_rawDescGZIP(), []int{3}
}

func (x *SubmarineRepayData) GetPrivkey() []byte {
	if x != nil {
		return x.Privkey
	}
	return nil
}

func (x *SubmarineRepayData) GetScript() []byte {
	if x != nil {
		return x.Script
	}
	return nil
}

func (x *SubmarineRepayData) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *SubmarineRepayData) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SubmarineRepayData) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SubmarineRepayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*SubmarineRepayData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *SubmarineRepayRequest) Reset() {
	*x = SubmarineRepayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lspclient_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmarineRepayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmarineRepayRequest) ProtoMessage() {}

func (x *SubmarineRepayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lspclient_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmarineRepayRequest.ProtoReflect.Descriptor instead.
func (*SubmarineRepayRequest) Descriptor() ([]byte, []int) {
	return file_lspclient_proto_rawDescGZIP(), []int{4}
}

func (x *SubmarineRepayRequest) GetData() []*SubmarineRepayData {
	if x != nil {
		return x.Data
	}
	return nil
}

type QueryRoutePaymentResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentHash string `protobuf:"bytes,1,opt,name=payment_hash,json=paymentHash,proto3" json:"payment_hash,omitempty"`
	Status      int32  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Failure     int32  `protobuf:"varint,3,opt,name=failure,proto3" json:"failure,omitempty"`
}

func (x *QueryRoutePaymentResult) Reset() {
	*x = QueryRoutePaymentResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lspclient_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRoutePaymentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRoutePaymentResult) ProtoMessage() {}

func (x *QueryRoutePaymentResult) ProtoReflect() protoreflect.Message {
	mi := &file_lspclient_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRoutePaymentResult.ProtoReflect.Descriptor instead.
func (*QueryRoutePaymentResult) Descriptor() ([]byte, []int) {
	return file_lspclient_proto_rawDescGZIP(), []int{5}
}

func (x *QueryRoutePaymentResult) GetPaymentHash() string {
	if x != nil {
		return x.PaymentHash
	}
	return ""
}

func (x *QueryRoutePaymentResult) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *QueryRoutePaymentResult) GetFailure() int32 {
	if x != nil {
		return x.Failure
	}
	return 0
}

var File_lspclient_proto protoreflect.FileDescriptor

var file_lspclient_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x73, 0x70, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6c, 0x73, 0x70, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0xa2, 0x01, 0x0a,
	0x19, 0x53, 0x75, 0x62, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x65, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x72,
	0x65, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x70,
	0x61, 0x79, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0c, 0x72, 0x65, 0x70, 0x61, 0x79, 0x50, 0x72, 0x69, 0x76, 0x6b, 0x65, 0x79, 0x12, 0x21,
	0x0a, 0x0c, 0x72, 0x65, 0x70, 0x61, 0x79, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x61, 0x79, 0x50, 0x75, 0x62, 0x6b, 0x65,
	0x79, 0x22, 0x91, 0x01, 0x0a, 0x17, 0x53, 0x75, 0x62, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1f, 0x0a,
	0x0b, 0x68, 0x74, 0x6c, 0x63, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0a, 0x68, 0x74, 0x6c, 0x63, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x15, 0x53, 0x75, 0x62, 0x6d, 0x61, 0x72,
	0x69, 0x6e, 0x65, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x69, 0x6e, 0x5f, 0x74, 0x78, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x69, 0x6e, 0x54, 0x78, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6e, 0x5f, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x6e, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x69, 0x6e, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x88, 0x01,
	0x0a, 0x12, 0x53, 0x75, 0x62, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x70, 0x61, 0x79,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x6b, 0x65, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4a, 0x0a, 0x15, 0x53, 0x75, 0x62, 0x6d,
	0x61, 0x72, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x70, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x6c, 0x73, 0x70, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x75, 0x62, 0x6d,
	0x61, 0x72, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x70, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x6e, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x66, 0x61, 0x69,
	0x6c, 0x75, 0x72, 0x65, 0x2a, 0x5b, 0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x14, 0x49, 0x4e, 0x54, 0x45, 0x47,
	0x52, 0x49, 0x54, 0x59, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x54, 0x45, 0x47, 0x52, 0x49, 0x54, 0x59, 0x52, 0x45,
	0x53, 0x55, 0x4c, 0x54, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x54,
	0x45, 0x47, 0x52, 0x49, 0x54, 0x59, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x4e, 0x47, 0x10,
	0x02, 0x42, 0x36, 0x42, 0x09, 0x4c, 0x73, 0x70, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5a, 0x29,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x6e, 0x69, 0x6e, 0x67, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x6c, 0x6e, 0x64, 0x2f,
	0x6c, 0x73, 0x70, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_lspclient_proto_rawDescOnce sync.Once
	file_lspclient_proto_rawDescData = file_lspclient_proto_rawDesc
)

func file_lspclient_proto_rawDescGZIP() []byte {
	file_lspclient_proto_rawDescOnce.Do(func() {
		file_lspclient_proto_rawDescData = protoimpl.X.CompressGZIP(file_lspclient_proto_rawDescData)
	})
	return file_lspclient_proto_rawDescData
}

var file_lspclient_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lspclient_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_lspclient_proto_goTypes = []interface{}{
	(IntegrityResult)(0),              // 0: lspclient.IntegrityResult
	(*SubmarineCreateKeysResult)(nil), // 1: lspclient.SubmarineCreateKeysResult
	(*SubmarineRegisterResult)(nil),   // 2: lspclient.SubmarineRegisterResult
	(*SubmarineDetectResult)(nil),     // 3: lspclient.SubmarineDetectResult
	(*SubmarineRepayData)(nil),        // 4: lspclient.SubmarineRepayData
	(*SubmarineRepayRequest)(nil),     // 5: lspclient.SubmarineRepayRequest
	(*QueryRoutePaymentResult)(nil),   // 6: lspclient.QueryRoutePaymentResult
}
var file_lspclient_proto_depIdxs = []int32{
	4, // 0: lspclient.SubmarineRepayRequest.data:type_name -> lspclient.SubmarineRepayData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lspclient_proto_init() }
func file_lspclient_proto_init() {
	if File_lspclient_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lspclient_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmarineCreateKeysResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lspclient_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmarineRegisterResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lspclient_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmarineDetectResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lspclient_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmarineRepayData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lspclient_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmarineRepayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lspclient_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRoutePaymentResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lspclient_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lspclient_proto_goTypes,
		DependencyIndexes: file_lspclient_proto_depIdxs,
		EnumInfos:         file_lspclient_proto_enumTypes,
		MessageInfos:      file_lspclient_proto_msgTypes,
	}.Build()
	File_lspclient_proto = out.File
	file_lspclient_proto_rawDesc = nil
	file_lspclient_proto_goTypes = nil
	file_lspclient_proto_depIdxs = nil
}
